apiVersion: v1
kind: Service
metadata:
  name: flaresolverr
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.60
  labels:
    app: flaresolverr
spec:
  selector:
    app: flaresolverr
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 8191   
      targetPort: 8191
