apiVersion: v1
kind: Service
metadata:
  name: seerr
  labels:
    app: seerr
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.53
spec:
  selector:
    app: seerr
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 5055        
      targetPort: 5055
