apiVersion: v1
kind: Service
metadata:
  name: seerr
  labels:
    app: seerr
spec:
  selector:
    app: seerr
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 5055        
      targetPort: 5055
