apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbittorrent
  name: qbittorrent
  namespace: servarr
spec:
  selector:
    matchLabels:
      app: qbittorrent
  template:
    metadata:
      labels:
        app: qbittorrent
    spec:
      initContainers:
        - image: ghcr.io/qdm12/gluetun:latest
          name: gluetun
          imagePullPolicy: Always
          restartPolicy: Always # Run as sidecar
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 9091
          env:
            - name: TZ
              value: America/New_York
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-secret
                  key: wireguard-pk
            - name: VPN_PORT_FORWARDING
              value: on
            - name: VPN_PORT_FORWARDING_UP_COMMAND
              value: /bin/sh -c 'wget -O- --retry-connrefused --post-data "json={\"listen_port\":{{PORTS}}}" http://localhost:9091/api/v2/app/setPreferences 2>&1'
            - name: DNS_ADDRESS
              value: "8.8.8.8"
            #- name: FIREWALL_INPUT_PORTS
            #  value: "9091"
      containers:
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: WEBUI_PORT
              value: "9091"        # move Web UI to 9091 as you had before
          ports:
            - containerPort: 9091   # Web UI
              name: webui
            - containerPort: 6881   # BitTorrent TCP
              name: bt-tcp
            - containerPort: 6881   # BitTorrent UDP
              name: bt-udp
              protocol: UDP
          volumeMounts:
            - name: qb-config
              mountPath: /config
            - name: qb-downloads
              mountPath: /downloads
      volumes:
        - name: qb-config
          persistentVolumeClaim:
            claimName: qbittorrent-config-pvc
        - name: qb-downloads
          persistentVolumeClaim:
            claimName: jellyfin-media-pvc
