apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: qbittorrent
  name: qbittiorrent
  namespace: servarr
spec:
  selector:
    matchLabels:
      app: qbittiorrent
  template:
    metadata:
      labels:
        app: qbittiorrent
    spec:
      containers:
        - image: ghcr.io/qdm12/gluetun:latest
          name: gluetun
          imagePullPolicy: Always
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
          ports:
            - containerPort: 9091
          env:
            - name: TZ
              value: America/New_York
            - name: VPN_SERVICE_PROVIDER
              value: protonvpn
            - name: VPN_TYPE
              value: wireguard
            - name: WIREGUARD_PRIVATE_KEY
              valueFrom:
                secretKeyRef:
                  name: wireguard-secret
                  key: wireguard-pk
            - name: VPN_PORT_FORWARDING
              value: on
            #- name: FIREWALL_INPUT_PORTS
            #  value: "9091"
        - name: qbittorrent
          image: lscr.io/linuxserver/qbittorrent:latest
          imagePullPolicy: Always
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: America/New_York
            - name: WEBUI_PORT
              value: "9091"        # move Web UI to 9091 as you had before
          ports:
            - containerPort: 9091   # Web UI
              name: webui
            - containerPort: 6881   # BitTorrent TCP
              name: bt-tcp
            - containerPort: 6881   # BitTorrent UDP
              name: bt-udp
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities: { drop: ["ALL"] }

