apiVersion: v1
kind: Service
metadata:
  name: qbittorrent
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.69
  labels:
    app: qbittorrent
spec:
  selector:
    app: qbittorrent
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9091     
      targetPort: 9091
