apiVersion: v1
kind: Service
metadata:
  name: prowlarr
  labels:
    app: prowlarr
spec:
  selector:
    app: prowlarr
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 9696        
      targetPort: 9696  
