apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  type: ClusterIP 
  ports:
    - name: http
      protocol: TCP
      port: 8096         
      targetPort: 8096  
---
apiVersion: v1
kind: Service
metadata:
  name: jellyfin-local-discovery
  labels:
    app: jellyfin
spec:
  selector:
    app: jellyfin
  type: LoadBalancer
  ports:
    - name: local-discovery
      port: 8096         
      targetPort: 8096  
    - name: dlna
      port: 1900
      targetPort: 1900
