apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    chart: cert-manager
    repoURL: oci://quay.io/jetstack/charts/cert-manager
    targetRevision: v1.19.1
    helm:
      values: |
        crds:
          enabled: true
  destination:
    name: "in-cluster"
    namespace: cert-manager
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

