apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: grafana
  namespace: argocd
spec:
  project: default
  sources:
    - chart: grafana
      repoURL: https://grafana.github.io/helm-charts
      targetRevision: 9.2.1
      helm:
        releaseName: grafana
        values: |
          persistence:
            enabled: true
            type: pvc
            accessModes: [ReadWriteOnce]
            size: 10Gi
            storageClassName: longhorn 
            finalizers:
              - kubernetes.io/pvc-protection
          initChownData:
            enabled: true
          podSecurityContext:
            fsGroup: 472
    - path: lgtm/grafana
      repoURL: https://github.com/Josh-cannot-code/personal-cluster
      targetRevision: HEAD
  destination:
    name: "in-cluster"
    namespace: lgtm
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

