apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomize-example
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: examples/helloWorld
    repoURL: 'https://github.com/kubernetes-sigs/kustomize'
    targetRevision: HEAD
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'

