apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-storage-class
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    path: nfs
    repoURL: 'https://github.com/Josh-cannot-code/personal-cluster.git'
    targetRevision: HEAD
  destination:
    name: "in-cluster"
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

