apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nfs-storage-class
  namespace: argocd
spec:
  project: default
  source:
    chart: nfs-subdir-external-provisioner
    repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
    targetRevision: 4.0.18
    helm:
      values: |
        nfs:
          server: 192.168.18.13
          path: /mnt/wd-usb-hhd/srv/nfs/k8s
        storageClass:
          reclaimPolicy: Retain
  destination:
    name: "in-cluster"
    namespace: nfs-provisioner
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
