apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seerr
  namespace: argocd
spec:
  project: default
  source:
    chart: seerr-chart
    repoURL: https://github.com/seerr-team/seerr.git
    targetRevision: 3.0.0
  destination:
    name: "in-cluster"
    namespace: jellyfin
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
