apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-crd
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/"

  managedKubeSecretReferences:
    - secretName: test-secret
      secretNamespace: default
      creationPolicy: "Orphan"
    - secretName: cloudflare-api-token-secret
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        api-token: "{{ .KEY.SecretPath }} {{ .KEY.Value}}"
