apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: infisicalsecret-crd
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    serviceToken:
      serviceTokenSecretReference:
        secretName: service-token
        secretNamespace: default
      secretsScope:
        envSlug: prod
        secretsPath: "/"

  managedKubeSecretReferences:
    - secretName: cloudflare-api-token-secret
      secretNamespace: cert-manager
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
    - secretName: regcred
      secretNamespace: psa
      creationPolicy: "Orphan"
      secretType: kubernetes.io/dockerconfigjson
      template:
        includeAllSecrets: true
    - secretName: cf-ddns-secret
      secretNamespace: cloudflare
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
    - secretName: wireguard-secret
      secretNamespace: servarr
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
    - secretName: pihole-secret
      secretNamespace: pihole
      creationPolicy: "Orphan"
      template:
        includeAllSecrets: true
        #data:
        #  api-token: "{{ .api-token.Value }}"
