apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: cf-issuer
  namespace: cert-manager
spec:
  acme:
    solvers:
    - dns01:
        cloudflare:
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
