apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
spec:
  selector:
    app: radarr
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 7878        
      targetPort: 7878
