apiVersion: v1
kind: Service
metadata:
  name: radarr
  labels:
    app: radarr
  annotations:
    metallb.io/loadBalancerIPs: 192.168.18.54
spec:
  selector:
    app: radarr
  type: LoadBalancer
  ports:
    - name: http
      protocol: TCP
      port: 7878        
      targetPort: 7878
